= Red Hat JBoss EAP Administration II
:navtitle: Home

== Introduction

Welcome to this quick course on _Advanced JBoss EAP Administration_.
This course is the `third` in a series of `four` courses about Red Hat JBoss EAP:

. Introduction to Red Hat JBoss EAP
.. https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D59719403[For Red Hat Associates^]
.. https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D59719502[For Red Hat Partners^]
. https://redhatquickcourses.github.io/eap-admin1[Red Hat JBoss EAP Administration I^]
. *Red Hat JBoss EAP Administration II (_This course_)*
. https://demo.redhat.com/catalog?search=eap+8&item=babylon-catalog-prod%2Fsandboxes-gpte.jboss-eap-migration.prod[Migrating to Red Hat JBoss EAP 8^]

This course covers advanced JBoss EAP installation and upgrade methods, JBoss EAP Domain mode configuration and management, clustering, security and high availability. You also learn about deploying JBoss EAP applications on the OpenShift Container Platform.

NOTE: The hands-on labs for this course have been tested on *JBoss EAP 8.0*. The labs should mostly work in minor update releases of EAP 8. If you encounter any issues, please open a GitHub issue in the course repository.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Yogita Soni
* Ashish Shah
* Rutuja Deshmukh
* Abhijit Humbe

== Classroom Environment

NOTE: We are planning to provide a classroom environment for Red Hat associates and select Red Hat partners on the Red Hat Demo Platform (RHDP). This is a work in progress. Classroom links will be updated here as and when the classroom is ready. Leave a https://github.com/RedHatQuickCourses/eap-admin1/issues/16#issue-2300120102[comment or +1 this issue^] to up vote. Until then, we recommend using your own servers or VMs to run the hands-on labs in this learning path.

For the hands-on labs in this course, you need to provision the following:

* 3 RHEL 9 or CentOS Stream 9 VMs - each with at least 8 vCPU, 16GB RAM, 2 NICs and 80GB hard disk
* An OpenShift Container Platform cluster with at least 8vCPU, 16GB RAM, 100GB disk. You can provision a cluster using any of the below listed modalities:
** Bare metal, VMs or on OpenStack
** Single Node OpenShift (SNO) cluster
** OpenShift Local
** Red Hat Hybrid Cloud Console (https://console.redhat.com)
** OpenShift on Hyperscaler clouds - ROSA or ARO

== Prerequisites

* Basic knowledge of Linux and JBoss EAP administration
* Basic knowledge of Java and deploying applications on the Java Virtual Machine (JVM)
* Knowledge of building Docker or Podman containers
* Basics of deploying applications on OpenShift Container Platform
* Sign up for a free Red Hat Developer account if you don't have one at https://developer.redhat.com

== Objectives

The overall objectives of this course include:

* Automated installation using JBoss EAP Installer Response files
* JBoss EAP Domain mode configuration and deployment
* JVM configuration and optimization for JBoss EAP applications
* Clustering and High Availability in JBoss EAP
* Securing JBoss EAP Applications
* Configuring OpenID Connect which was introduced with EAP 8.0