= Red Hat JBoss EAP Administration II
:navtitle: Home

== Introduction

Welcome to this quick course on _Advanced JBoss EAP Administration_.
This course is the `third` in a series of `seven` courses about Red Hat JBoss EAP:

1. Introduction to Red Hat JBoss EAP (_Under Development_)
2. Red Hat JBoss EAP Administration I  (_Under Development_)
3. *Red Hat JBoss EAP Administration II (_This course_)*
4. Migrating to Red Hat JBoss EAP 8 (_Under Development_)
5. Red Hat JBoss EAP 8 Deployment in Public Cloud Infrastructures (_Under Development_)
6. Developing Applications for Red Hat JBoss EAP 8 (_Under Development_)
7. Red Hat JBoss EAP 8 Workshop (_Under Development_)

This course covers advanced JBoss EAP installation and upgrade methods, JBoss EAP Domain mode configuration and management, clustering, security and high availability. You also learn about deploying JBoss EAP applications on the OpenShift Container Platform.

NOTE: The hands-on labs for this course have been tested on *JBoss EAP 8.0*. The labs should mostly work in minor update releases of EAP 8. If you encounter any issues, please open a GitHub issue in the course repository.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Yogita Soni
* Ashish Shah
* Rutuja Deshmukh
* Abhijit Humbe

== Classroom Environment

=== For Red Hat Associates

Red Hat associates and others who have access to the Red Hat Demo Platform (RHDP) should continue to use the _TBD_ catalog item that you provisioned in the _Red Hat JBoss EAP Administration I_ course.

=== For Red Hat Partners

Red Hat partners and others who do not have access to RHDP, should provision the following on their own infrastructure:

* 2 RHEL 9 or CentOS Stream 9 VMs - each with at least 8 vCPU, 16GB RAM, 2 NICs and 80GB hard disk
* An OpenShift Container Platform cluster with at least 8vCPU, 16GB RAM, 100GB disk. You can provision a cluster using any of the below listed modalities:
** Bare metal, VMs or on OpenStack
** Single Node OpenShift (SNO) cluster
** OpenShift Local
** Red Hat Hybrid Cloud Console (https://console.redhat.com)
** OpenShift on Hyperscaler clouds - ROSA or ARO

NOTE: TODO: Add more details of DNS names, IPs and a nice network diagram

== Prerequisites

* Basic knowledge of Linux and JBoss EAP administration
* Basic knowledge of Java and deploying applications on the Java Virtual Machine (JVM)
* Knowledge of building Docker or Podman containers
* Basics of deploying applications on OpenShift Container Platform
* Sign up for a free Red Hat Developer account if you don't have one at https://developer.redhat.com

== Objectives

The overall objectives of this course include:

* Automated installation using JBoss EAP Installer Response files
* Automated installation and configuration of JBoss EAP using Ansible Middleware
* JBoss EAP Domain mode configuration and deployment
* JVM configuration and optimization for JBoss EAP applications
* Clustering and High Availability in JBoss EAP
* Securing JBoss EAP Applications
* Configuring OpenID Connect which was introduced with EAP 8.0
* Deploying EAP applications on OpenShift