site:
  title: Red Hat JBoss EAP 8 Administration II
  start_page: eap-admin2::index.adoc

content:
  sources:
    - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
