= Load Balancing JBoss EAP Instances

== References

* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html/configuration_guide/configuring_high_availability#configuring_jboss_eap_load_balancer[JBoss EAP Load Balancer]

== Exercise: Load Balancing JBoss EAP Instances using mod_undertow

=== Pre-requisites

* For the exercises in this chapter, you will need *three (3)* servers or VMs with JBoss EAP 8.0 installed on them. Your IP addresses maybe different. Replace the values according to your set up.
+
[cols="1,1,1"]
|===
|*Host*|*IP Address*|*Role*
|`controller.example.com`
|`192.168.124.10`
|`Load Balancer`

|`eap1.example.com`
|`192.168.124.11`
|`Cluster Node`

|`eap2.example.com`
|`192.168.124.12`
|`Cluster Node`
|===

* Install JBoss EAP 8.0 on all three servers. We recommend using the zip file installation method and installing it in a separate directory to prevent overwriting the configuration of the instance that you have used in previous exercises. For all VMs, create a user named `jboss` that will run the JBoss EAP instance.

* Configure UDP or TCP based clustering on `eap1` and `eap2` by referring to the previous sections in this chapter. Ensure the appropriate TCP and UDP ports are open in the firewall as outlined in the previous sections.

=== Steps

. Inspect the default `$JBOSS_HOME/standalone/configuration/standalone-load-balancer.xml`. This file is much much smaller compared to the default `standalone-*.xml` files. It contains only a few modules pertaining to load balancing and web serving. You will mainly configure the load balancer in the `undertow` subsystem section of this file.
+
```xml
...
<extensions>
  <extension module="org.jboss.as.logging"/>
  <extension module="org.wildfly.extension.elytron"/>
  <extension module="org.wildfly.extension.io"/>
  <extension module="org.wildfly.extension.undertow"/>
...
</extensions>
```

. The load balancer will receive HTTP requests on port `8080` and then load balance the requests between the two standalone EAP instances `eap1` and `eap2` running on two separate similarly named VMs. Like you did in previous sections, you need to allow the traffic on this port through the operating system firewall. The load balancer also communicates with the backend EAP instances on TCP port `8009`. You need to also open this port on the `eap1` and `eap2` instances. Start by opening port `8080` on the `controller` VM:
+
```bash
root@controller $ firewall-cmd --zone=public --permanent --add-port=8080/tcp
root@controller $ firewall-cmd --reload
```

. Also, open TCP port `8009` on both `eap1` and `eap2`:
+
```bash
root@eap1 $ firewall-cmd --zone=public --permanent --add-port=8009/tcp
root@eap1 $ firewall-cmd --reload
```
+
```bash
root@eap2 $ firewall-cmd --zone=public --permanent --add-port=8009/tcp
root@eap2 $ firewall-cmd --reload
```

. Start the two backend EAP instances (You can start either the UDP or TCP based cluster like in previous sections). In this case, I am starting the UDP based cluster.
+
```bash
[jboss@eap1 bin] $ ./standalone.sh -c standalone-full-ha.xml \
  -Djboss.bind.address=192.168.124.11 \
  -Djboss.bind.address.private=192.168.124.11 \
  -Djboss.node.name=eap1 \
  -Djboss.messaging.cluster.password=redhat123
```
+
```bash
[jboss@eap2 bin] $ ./standalone.sh -c standalone-full-ha.xml \
  -Djboss.bind.address=192.168.124.12 \
  -Djboss.bind.address.private=192.168.124.12 \
  -Djboss.node.name=eap2 \
  -Djboss.messaging.cluster.password=redhat123
```
+
IMPORTANT: The node name is required to use the sticky session feature.

. Now, start the load balancer on the `controller` VM.
+
```bash
[jboss@eap1 bin] $ ./standalone.sh -c standalone-load-balancer.xml \
  -Djboss.bind.address=192.168.124.10
...
WFLYUT0003: Undertow 2.3.10.SP3-redhat-00001 starting
WFLYUT0012: Started server default-server.
WFLYUT0006: Undertow HTTP listener default listening on 192.168.124.10:8080
...
UT005039: Undertow starts mod_cluster proxy advertisements on /224.0.1.105:23364 with frequency 10000 ms
WFLYSRV0212: Resuming server
...
WFLYSRV0025: JBoss EAP 8.0.0.GA (WildFly Core 21.0.5.Final-redhat-00001) started in 9772ms - Started 109 of 120 services (43 services are lazy, passive or on-demand) - Server configuration file in use: standalone-load-balancer.xml
```

. If you have not done so already, download the https://github.com/RedHatQuickCourses/eap-qc-apps/releases/download/eap8-lp/cluster.war WAR file. Copy the WAR file to the `/tmp` folder on both `eap1` and `eap2` and deploy it as outlined in the previous sections.
+
WARNING: Do *NOT* deploy the WAR file on the `controller` VM running the load balancer!

. Configure the load balancer to load balance requests between the two EAP instances. Execute the following EAP CLI commands on the *controller* VM. To configure a new load balancer, create a `cluster-handler` reverse proxy in the `undertow` subsystem:
+
```bash
jboss@controller bin $ ./jboss-cli.sh --connect 
[standalone@localhost:9990 /] /subsystem=undertow/configuration=handler/reverse-proxy=cluster-handler:add
{"outcome" => "success"}
```

. Create a `remote-eap1` outbound socket binding to `eap1` on TCP port `8009`. 
+
```bash
/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=remote-eap1:add(host=192.168.124.11, port=8009)
{"outcome" => "success"}
```

. Create a reference to the `remote-eap1` socket binding in the `undertow` subsystem. Bind it with the `AJP` scheme and the context path for the application:
+
```bash
/subsystem=undertow/configuration=handler/reverse-proxy=cluster-handler/host=eap1:add(outbound-socket-binding=remote-eap1, scheme=ajp, instance-id=eap1, path=/cluster)
```
+
IMPORTANT: For sticky sessions to work correctly, the `instance-id` attribute should have the same
value specified by the `jboss.node.name` system property during backend EAP instance startup.

. Repeat the above steps for creating socket bindings and handlers for `eap2`
+
```bash
/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=remote-eap2:add(host=192.168.124.12, port=8009)

/subsystem=undertow/configuration=handler/reverse-proxy=cluster-handler/host=eap2:add(outbound-socket-binding=remote-eap2, scheme=ajp, instance-id=eap2, path=/cluster)
```

. Finally, create a new reverse proxy location named `/cluster`, and refer it to the `cluster-handler` handler:
+
```bash
/subsystem=undertow/server=default-server/host=default-host/location=\/cluster:add(handler=cluster-handler)

:reload
```
+
NOTE: Note the `\` before the `/cluster` URL. It's an escape handler because the URL needs an explicit `/`, which also happens to be the namespacing operator for the EAP CLI.

. You have now configured the load balancer for the application. To view the changes from the default configuration, see https://github.com/RedHatQuickCourses/eap-qc-apps/blob/main/admin2/load-balancer.diff

. The load balancer in EAP comes with session stickiness enabled. So you can test the clustering behavior using a browser. Navigate to the load balancer URL at http://192.168.124.10:8080/cluster. The load balancer may forward the request to either `eap1` or `eap2`, and your output maybe different. In my case, the load balancer forwarded the request to `eap1`.

. Refresh the page a few times and observe the counter value incrementing by one for every request. Also note that the load balancer always sends requests to the same EAP instance (in my case `eap1`) that served the first request from this browser client.

. Kill the EAP node that is currently serving requests. Observe that the cluster detects the failure and rebalances.

. Make another request to the load balancer at http://192.168.124.10:8080/cluster. Observe that requests are now sent to the other remaining live node - `eap2`, but the counter value is not reset to zero, but keeps incrementing on every page request.

. Optional. Test failback. Restart the node you killed earlier. Kill the node that was serving the latest request. Send more requests to the load balancer, and verify that the counter value is not reset, but keeps on incrementing.
