= Enabling TLS/SSL in the EAP Web Console

== References

* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8.0/html-single/configuring_ssltls_in_jboss_eap/index#enabling-one-way-ssl-tls-for-management-interfaces-by-using-the-subsystem-commands_enabling-one-way-ssl-tls-for-management-interfaces[Enabling TLS for EAP Web Console^]

* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8.0/html-single/configuring_ssltls_in_jboss_eap/index#disabling-ssl-tls-for-management-interfaces-by-using-the-security-command_enabling-one-way-ssl-tls-for-management-interfaces[Disabling TLS for EAP Web Console^]

* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/8.0/html-single/configuring_ssltls_in_jboss_eap/index#enabling-one-way-ssl-tls-for-management-interfaces-by-using-the-subsystem-commands_enabling-one-way-ssl-tls-for-management-interfaces[EAP CLI configuration for enabling web console TLS^]


== Exercise: Enabling and Disabling TLS for the EAP Web Console

. Start JBoss EAP as the `jboss` user.

. Navigate to https://eap1:8443. By default, JBoss EAP generates a self-signed certificate for applications on start up. Inspect the start up logs:
+
```
...
...WFLYELY01085: Generated self-signed certificate at ...jboss-eap-8.0/standalone/configuration/application.keystore. Please note that self-signed certificates are not secure and should only be used for testing purposes. Do not use this self-signed certificate in production.
SHA-1 fingerprint of the generated key is 2a:6f:bd:4c:76:7a:ab:a0:e5:1e:a5:ed:31:5c:28:83:02:d3:7a:63
SHA-256 fingerprint of the generated key is 2a:80:21:67:e2:c1:64:75:9d:14:1d:ea:87:c8:c4:ec:86:a7:5e:40:16:01:f5:5b:94:32:37:85:07:c7:ca:5a
...
```

. The EAP CLI offers convienient short cut commands to enable TLS for the EAP web console. Connect to the EAP CLI and run the following command to create a new self-signed certificate for the web console. You will be asked a sequence of questions. An example interactive session output is given below:
+
```bash
[standalone@localhost:9990 /] security enable-ssl-management --interactive
Please provide required pieces of information to enable SSL:

Certificate info:
Key-store file name (default management.keystore): 
Password (blank generated): redhat123
What is your first and last name? [Unknown]: EAP Admin
What is the name of your organizational unit? [Unknown]: MyOrg
What is the name of your organization? [Unknown]: RedHat
What is the name of your City or Locality? [Unknown]: Raleigh
What is the name of your State or Province? [Unknown]: North Caroline
What is the two-letter country code for this unit? [Unknown]: NC
Is CN=EAP Admin, OU=MyOrg, O=RedHat, L=Raleigh, ST=North Caroline, C=NC correct y/n [y]?y
Validity (in days, blank default): 30
Alias (blank generated): 
Enable SSL Mutual Authentication y/n (blank n):n

SSL options:
key store file: management.keystore
distinguished name: CN=EAP Admin, OU=MyOrg, O=RedHat, L=Raleigh, ST=North Caroline, C=NC
password: redhat123
validity: 30
alias: alias-ffd473f8-e220-4d46-9d41-549dc4085427
Server keystore file management.keystore, certificate file management.pem and management.csr file will be generated in server configurat
ion directory.

Do you confirm y/n :y
Unable to connect due to unrecognised server certificate
Subject    - CN=EAP Admin,OU=MyOrg,O=RedHat,L=Raleigh,ST=North Caroline,C=NC
Issuer     - CN=EAP Admin, OU=MyOrg, O=RedHat, L=Raleigh, ST=North Caroline, C=NC
Valid From - Mon May 06 11:42:43 IST 2024
Valid To   - Wed Jun 05 11:42:43 IST 2024
MD5 : e7:b2:f1:87:1f:88:e7:8b:df:c8:a1:07:75:7a:0c:47
SHA1 : 49:ab:d9:37:83:f6:39:a5:46:60:1b:5f:c2:83:26:df:a6:5a:09:e1

Accept certificate? [N]o, [T]emporarily, [P]ermanently : P
Server reloaded.
SSL enabled for http-interface
ssl-context is ssl-context-ffd473f8-e220-4d46-9d41-549dc4085427
key-manager is key-manager-ffd473f8-e220-4d46-9d41-549dc4085427
key-store   is key-store-ffd473f8-e220-4d46-9d41-549dc4085427
```

. Make note of the long UUID value for the `key-store`. You can reference this unique ID for CLI operations on the keystore. Navigate to https://eap1:9993 to access the web console using TLS.

. The EAP CLI also offers a convenient interactive tool to generate production quality TLS certificates for *Let's Encrypt*. See https://wildfly-security.github.io/wildfly-elytron/blog/obtaining-certificates-from-lets-encrypt-using-the-wildfly-cli/ for more details.

. To disable TLS for the web console, run the following command:
+
```bash
[standalone@localhost:9993 /] security disable-ssl-management
Server reloaded.
Reconnected to server.
SSL disabled for http-interface
```

. To re-enable TLS with the certificate you created earlier, run the following:
+
```bash
[standalone@localhost:9990 /] security enable-ssl-management --key-store-name=key-store-ffd473f8-e220-4d46-9d41-549dc4085427
Server reloaded.
SSL enabled for http-interface
ssl-context is ssl-context-ffd473f8-e220-4d46-9d41-549dc4085427
key-manager is key-manager-ffd473f8-e220-4d46-9d41-549dc4085427
key-store   is key-store-ffd473f8-e220-4d46-9d41-549dc4085427
```