= Installing JBoss EAP Using an Automated Installer Script
:navtitle: Automated Installer Script

In the https://redhatquickcourses.github.io/eap-admin1[previous course] on basic JBoss EAP Administration, you learnt how to install JBoss EAP using the installation jar file. As a last step in the GUI installer, you were given the choice of saving your installation options as an XML file (`myinstall.xml`).

You can use this XML file, along with a `variables` file (typically with the same name as the XML file but with a file extension of `.variables`, for example `myinstall.variables`), to provision JBoss EAP instances on other servers in an *automated* manner (non-interactive, unattended installation). This approach gives you flexibility to roll out JBoss EAP instances across multiple servers using wrapper shell scripts, configuration management tools like Ansible, Terraform, Puppet, and more.

TIP: You can version control the automated installer XML file and the `.variables` file in Git and optionally use GitOps and Infrastructure as Code (IaC) techniques to roll out JBoss EAP instances in your development, staging, QA and Production environments.

[TIP]
====
You need not copy the installer XML files and variables file to every system. You can serve these files over http or ftp and pass the location to the installer JAR as arguments:

$ *java -jar installer.jar http://myhost/myinstall.xml -variablesfile http://myhost/myinstall.xml.variables*
====

WARNING: The automated installer is not backward compatible! You cannot use an installation script generated from a previous version of JBoss EAP to install a new version. Only use installation scripts generated by the same version of JBoss EAP.

== References

* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/installation_guide/index#automated-installer-installation_default[Using the automated installer installation]

== Lab: Install JBoss EAP using the Automated Installer

=== Pre-requisites

* You should have previously installed JBoss EAP using the JAR installer and saved the installation options into an automated installer XML file.

* Alternatively, you can download sample https://raw.githubusercontent.com/RedHatQuickCourses/eap-qc-apps/main/admin1/eap-automated/myinstall.xml[myinstall.xml] and https://raw.githubusercontent.com/RedHatQuickCourses/eap-qc-apps/main/admin1/eap-automated/myinstall.xml.variables[myinstall.xml.variables] files, and copy it to the machine where you want to install JBoss EAP

=== Steps

. If you have a `myinstall.xml` automated installation file from a previous GUI installation, then you can use it in this lab. Ensure that you edit the `myinstall.xml.variables` file and enter the password for the `admin` user, otherwise the installer will prompt you for the password.

. If you download the sample https://raw.githubusercontent.com/RedHatQuickCourses/eap-qc-apps/main/admin1/eap-automated/myinstall.xml[myinstall.xml] and https://raw.githubusercontent.com/RedHatQuickCourses/eap-qc-apps/main/admin1/eap-automated/myinstall.xml.variables[myinstall.xml.variables] files, then you need to edit both files and change some values before you proceed with the installation.

. Copy both files to the server where you want to install JBoss EAP. Inspect the `myinstall.xml` file. This file was captured from a JBoss EAP installation using the installer JAR file, and it customizes the installation with the following options:

* Adds a credential store where you can store sensitive information like passwords in encrypted form
* Replaces the default JSF implementation (`Mojarra`) with `Apache MyFaces`

. Edit the `myinstall.xml` file and change the following. `TODO` markers have been added to this file in places where you need to change the default value.

.. Replace the */path/to/eap* with the full path to where you want to install JBoss EAP. If you want to run the installer as a non-root user, then you must make sure that the folder you enter here has the appropriate permissions to read and write files for non-root users. You can run the installer as a root user, or using `sudo` command, and then change the permissions and owner of the folder to run as a non-root user.
+
[source,xml]
----
<admin-user username="admin"/>
  <!-- TODO: CHANGE INSTALL PATH-->
  <target-directory>/path/to/eap</target-directory>
----

.. Replace the */path/to/credential.store* with the full path to where you want to create the credential store. Note that this value should be the full path to a *file* and not a *folder*. For example, to create the credential store in your user's home folder, the value should be */home/username/credential.store*.
+
[source,xml]
----
...
 <post-install-config name="add-credential-store">
  <attribute-list>
  <attribute>
    <name>path</name>
    <!-- TODO: CHANGE PATH TO CREDENTIAL STORE-->
    <value>/path/to/credential.store</value>
----

. Replace the */path/to/jsf-repo* with the full path to the *folder* where you want to store the JSF maven manifests.
+
[source,xml]
----
...
<attribute>
  <!-- TODO: CHANGE PATH TO JSF CHANNEL-->
  <name>localChannelPath</name>
  <value>/path/to/jsf-repo</value>
</attribute>
----

. Edit the `myinstall.xml.variables` file and add values for the `adminPassword` and `credential-store.password` keys. You will use the `adminPassword` value to access the EAP web console after installation.
+
```
adminPassword=redhat123
credential-store.password=redhat123
```

. Run the GUI installer and pass the `myinstall.xml` file as arguments
+
```bash
$ java -jar jboss-eap-8.0.0-installer.jar myinstall.xml
[ Starting automated installation ]
Selected components:
Red Hat JBoss Enterprise Application Platform
AppClient
Docs
Modules
Welcome Content
Installation Path: /home/rsriniva/test-eap-rsp
Maven Repositories:
 * https://maven.repository.redhat.com/ga/ 
Resolving feature-packs
100% ################################################## |
Installing packages
100% ################################################## |
Downloading components
100% ################################################## |
Installing modules
100% ################################################## |
Generating configuration
100% ################################################## |
Generating documentation
 Processing Complete
Cleanup
 Processing Complete
[ Installation Complete ]
[ Starting configuration tasks ]
Adding admin user
Advanced configuration - JSF Implementation
Advanced standalone-full-ha.xml configuration - Credential store
Advanced standalone-full-ha.xml configuration - JSF Implementation
Advanced standalone.xml configuration - Credential store
Advanced standalone.xml configuration - JSF Implementation
Advanced standalone-full.xml configuration - Credential store
Advanced standalone-full.xml configuration - JSF Implementation
Advanced standalone-ha.xml configuration - Credential store
Advanced standalone-ha.xml configuration - JSF Implementation
Advanced host.xml configuration - Credential store
Advanced host.xml configuration - JSF Implementation
Advanced host-primary.xml configuration - Credential store
Advanced host-primary.xml configuration - JSF Implementation
Advanced host-secondary.xml configuration - Credential store
Advanced host-secondary.xml configuration - JSF Implementation
[ Configuration tasks completed ]
```

. After the installation is completed, verify that a `credential.store` file, and a `jsf-repo` folder have been created in the path provided in the `myinstall.xml` file.

. In your new installation, start JBoss EAP using the `standalone.sh` script, and verify that you can log in to the JBoss EAP Management console at http://localhost:9990 using the `admin` username and the password you provided in the `myinstall.xml.variables`.